### ISSUE TITLE
Move Tasks

### ISSUE THREAD

**Issue by adrobisch** [commercetools/tresor#9]
This repo moved from `adrobisch/tresor` to `commercetools/tresor`. Tasks that could be considered as consequence:
* [x] rename package to `com.drobisch` to `com.commercetools`
* [x] move sonatype coordinates from `com.drobisch` to `com.commercetools` and check the the release it still working (environment variables might need re-adding)
* [x] publish the docs under the github pages of the new org and fix urls accordingly

@yanns I lost my admin role on this repo during the move, I would need that again to tackle some of these tasks. Could you add me please?

**Comment by yanns** [comment]
I've set @commercetools/ctp-backend as admin for this repo. OK for you?

**Comment by adrobisch** [comment]
done (https://github.com/commercetools/tresor/commit/e0e22f11348aa1d2d832b0ab8be418b2eb6af8a4) and released as `v0.8.1` with upgraded versions
